---
- name: Check binaries for calicoctl
  tags: ["calicoctl"]
  command: |
    artifact_name=calicoctl
    artifact_path={{ .work_dir }}/kubekey/cni/{{ .calico_version }}/{{ .item }}
    if [ ! -f $artifact_path/$artifact_name ]; then
      mkdir -p $artifact_path
      # download online
      http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.calicoctl .item }})
      if [ $http_code != 200 ]; then
        echo "http code is $http_code"
        exit 1
      fi
      curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.calicoctl .item }}
    fi
  loop: "{{ .artifact.arch | toJson }}"
  when: and .calico_version (ne .calico_version "")