---
- name: Cordon Node
  command: kubectl cordon {{ .inventory_name }}

- name: Drain Node
  command: kubectl drain {{ .inventory_name }} --ignore-daemonsets --delete-emptydir-data

- name: Delete Node
  command: kubectl delete node {{ .inventory_name }}

- name: Reset by Kubeadm
  command: kubeadm reset -f

- name: Remove Kube Services
  command: rm -rf /etc/systemd/system/kube*

- name: Delete Directories
  command: |
    rm -rf /etc/kubernetes/
    rm -rf /var/lib/kubelet/
    rm -rf {{ .work_dir }}
