---
- name: Check binaries for runc
  tags: ["runc"]
  command: |
    artifact_name={{ get .artifact.artifact_url.runc .item | splitList "/" | last }}
    artifact_path={{ .work_dir }}/kubekey/runc/{{ .runc_version }}/{{ .item }}
    if [ ! -f $artifact_path/$artifact_name ]; then
      mkdir -p $artifact_path
      # download online
      http_code=$(curl -Lo /dev/null -s -w "%{http_code}" {{ get .artifact.artifact_url.runc .item }})
      if [ $http_code != 200 ]; then
        echo "http code is $http_code"
        exit 1
      fi
      curl -L -o $artifact_path/$artifact_name {{ get .artifact.artifact_url.runc .item }}
    fi
  loop: "{{ .artifact.arch | toJson }}"
  when: and .runc_version (ne .runc_version "")