---
- name: Check binaries for hybridnet
  tags: ["hybridnet"]
  command: |
    artifact_name={{ .artifact.artifact_url.hybridnet | splitList "/" | last }}
    artifact_path={{ .work_dir }}/kubekey/cni
    if [ ! -f $artifact_path/$artifact_name ]; then
      mkdir -p $artifact_path
      # download online
      cd $artifact_path && helm pull {{ .artifact.artifact_url.hybridnet }}
    fi
  when: and .hybridnet_version (ne .hybridnet_version "")