---
- name: Check binaries for kubeovn
  tags: ["kubeovn"]
  command: |
    artifact_name={{ .artifact.artifact_url.kubeovn | splitList "/" | last }}
    artifact_path={{ .work_dir }}/kubekey/cni
    if [ ! -f $artifact_path/$artifact_name ]; then
      mkdir -p $artifact_path
      # download online
      cd $artifact_path && helm pull {{ .artifact.artifact_url.kubeovn }}
    fi
  when: and .kubeovn_version (ne .kubeovn_version "")