- hosts:
    - localhost
  roles:
    - init/init-artifact
    - init/init-cert
  tasks:
    - name: Export artifact
      command: |
        cd {{ .work_dir }}/kubekey && tar -czvf ../kubekey-artifact.tar.gz *
