---
- name: Delete Kubernetes
  hosts:
    - k8s_cluster
  roles:
    - capkk/kubernetes

- name: Delete Network
  hosts:
    - k8s_cluster
  roles:
    - capkk/network

- name: Delete ETCD
  hosts:
    - etcd
  roles:
    - capkk/etcd