---
- name: ETCD Binary Install Pre-Check
  hosts:
    - etcd
  gather_facts: true
  vars_files:
    - vars/cluster_requirements.yaml
  tasks:
    - name: Stop if arch supported
      assert:
        that: or (.cluster_require.supported_architectures.amd64 | has .os.architecture) (.cluster_require.supported_architectures.arm64 | has .os.architecture)
        success_msg: |
          {{- if .cluster_require.supported_architectures.amd64 | has .os.architecture }}
          amd64
          {{- else }}
          arm64
          {{- end }}
        fail_msg: "{{ .os.architecture }} is not a known arch"
      register: binary_type

# TODO: 需要讨论一个比较合适的 Install 流程，要统一安装目录等等
#- name: ETCD Binary Download
#  hosts:
#    - etcd
#  tags: ["etcd"]
#  vars_files:
#    - vars/init_artifact.yaml
#  pre_tasks:
#    - name: Create Directory
#      tags: [ "always" ]
#      command: |
#        if [ ! -d "{{ .work_dir }}" ]; then
#          mkdir -p {{ .work_dir }}/kubekey
#        fi
#  roles:
#    - capkk/download/curl/etcd

- name: ETCD Binary Install
  hosts:
    - etcd
  roles:
    - install/etcd